[default]
DEBUG = true
DATABASE = '/var/tmp/neteye.db'
SECRET_KEY = 'secret key'
SECURITY_REGISTERABLE = true
SECURITY_PASSWORD_SALT = 'salt'
SECURITY_SEND_REGISTER_EMAIL = false
SQLALCHEMY_DATABASE_URI = 'sqlite://///var/tmp/neteye.db'
TIMEOUT = 1
  [default.credentials]
    [default.credentials.1]
    USERNAME = 'admin'
    PASSWORD = 'cisco'
    ENABLE = 'cisco'
    [default.credentials.2]
    USERNAME = 'admin'
    PASSWORD = 'juniper'
    ENABLE = 'juniper'
    [default.credentials.3]
    USERNAME = 'admin'
    PASSWORD = 'cisco'
    ENABLE = 'cisco'

[development]


[production]